### ISSUE TITLE
Issuer country and name is missing from the Card payment method model

### ISSUE THREAD

**Issue by bsandman80** [morpher-ru/Yandex.Checkout.V3#15]
This is example json from the [documentation](https://checkout.yandex.com/developers/api#payment_object):

```` json
    "card": {
      "first6": "555555",
      "last4": "4444",
      "expiry_month": "07",
      "expiry_year": "2022",
      "card_type": "MasterCard",
      "issuer_country": "RU",
      "issuer_name": "Sberbank"
    },
````

**Comment by bzaar** [comment]
@bsandman80, thanks for raising this issue. Would you care to submit a fix? I'll then push out an updated package.

**Comment by bsandman80** [comment]
@bzaar sure, I was about to but wanted to give you guys a chance to respond to it first. Will look into it later today or tomorrow

**Comment by bsandman80** [comment]
Referenced this issue in pull request #16

**Comment by bzaar** [comment]
Published [Yandex.Checkout.V3.1.0.1.nupkg](https://www.nuget.org/packages/Yandex.Checkout.V3/1.0.1) Thank you for your contribution, @bsandman80!

**Comment by bsandman80** [comment]
Awesome, thanks for the swift response
