### ISSUE TITLE
Онлайн-кассы

### ISSUE THREAD

**Issue by Almeonamy** [morpher-ru/Yandex.Checkout.V3#2]
Не нашел возможности при создании платежа передать данные чека для онлайн-кассы.
https://kassa.yandex.ru/docs/guides/#prowedenie-platezha

Такой возможности нет или я плохо искал?

**Comment by bzaar** [comment]
Данные чека есть в [PR](https://github.com/morpher-ru/Yandex.Checkout.V3/pull/1/files#diff-81108e95ffb68c0dc51b0155f0ffedbbR48), который нужно-таки добить.

**Comment by bzaar** [comment]
Новая версия 0.1.0 (уже на nuget.org) позволяет передавать данные для чека.
