### ISSUE TITLE
Ошибка при использовании...

### ISSUE THREAD

**Issue by KANekT** [morpher-ru/Yandex.Checkout.V3#22]
"ClassName":"System.Net.WebException","Message":"Базовое соединение закрыто: Непредвиденная ошибка при передаче."

**Comment by KANekT** [comment]
рабочее решение найдено на
https://sitkodenis.ru/oshibka-v-webrequest-getresponse-i-protokol-https/

**Comment by BibendumRFID** [comment]
Ссылка не открывается

**Comment by bzaar** [comment]
@BibendumRFID Попробуйте перед вызовом сделать:

    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
