### ISSUE TITLE
Interfaces for Client and AsyncClient

### ISSUE THREAD

**Issue by alexanderkolbyoshkin** [morpher-ru/Yandex.Checkout.V3#24]
How about extracting interfaces from the Client and AsyncClient classes? This would allow to mock them in unit tests without additional wrappers.

**Comment by bzaar** [comment]
The recommended way of mocking HttpClient is... not to mock it. :) Instead, pass a mock implementation of HttpMessageHandler to HttpClient constructor. See https://stackoverflow.com/a/36427274/1291717
