### ISSUE TITLE
Невозможно отправить тело содержимого с данным типом предиката

### ISSUE THREAD

**Issue by sadomovalex** [morpher-ru/Yandex.Checkout.V3#27]
Добрый день, прежде всего спасибо за библиотеку.
Обнаружил следующую проблему: при попытке вызвать метод client.GetPayment(paymentId) выдается ошибка:

Невозможно отправить тело содержимого с данным типом предиката.
   в System.Net.HttpWebRequest.CheckProtocol(Boolean onRequestStream)
   в System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   в System.Net.HttpWebRequest.GetRequestStream()
   в Yandex.Checkout.V3.Client.CreateRequest(String method, Object body, String url, String idempotenceKey)
   в Yandex.Checkout.V3.Client.Query[T](String method, Object body, String url, String idempotenceKey)
   в Yandex.Checkout.V3.Client.GetPayment(String id)

Проблема в том, что для этого метода используется HTTP GET:
```
        public Payment GetPayment(string id)
            => Query<Payment>("GET", null, $"payments/{id}", null);
```

Но внутренний метод Query пытается при этом записать данные в request stream - т.к. этот метод также используется для POST запросов. Я пофиксил это вот так:

```
                string url = $"https://payment.yandex.net/api/v3/payments/{paymentId}";
                var request = (HttpWebRequest)WebRequest.Create(url);
                request.Method = "GET";
                request.Headers.Add("Authorization", "Basic " + Convert.ToBase64String(Encoding.UTF8.GetBytes(shopId + ":" + privateKey)));

                var response = this.requestSender.Send(request);
                string responseString = string.Empty;
                var responseEncoding = Encoding.UTF8;
                using (var sr = new StreamReader(response.GetResponseStream(), responseEncoding))
                {
                    responseString = sr.ReadToEnd();
                }

                return Serializer.DeserializeObject<Payment>(responseString);
```

Скорее всего такая же проблема у другого метода GetRefund в классе Client, который использует HTTP GET, хотя это я не проверял:
```
        public Refund GetRefund(string id)
            => Query<Refund>("GET", null, $"refunds/{id}", null);
```

**Comment by bzaar** [comment]
Добрый день! По-моему, это дубликат https://github.com/morpher-ru/Yandex.Checkout.V3/issues/25. Попробуйте последнюю версию библиотеки.

**Comment by bzaar** [comment]
Хотя нет, это похожая проблема, но не совсем та же. Та была в AsyncClient, а эта - в Client.

**Comment by bzaar** [comment]
Можете попробовать вот этот фикс? https://github.com/morpher-ru/Yandex.Checkout.V3/pull/28

**Comment by sadomovalex** [comment]
Попробовал - работает. Если опубликуете новую версию пакета nuget с этим фиксом, использую ее у себя

**Comment by bzaar** [comment]
Опубликовал [Yandex.Checkout.V3.1.0.5.nupkg](https://www.nuget.org/packages/Yandex.Checkout.V3/1.0.5).
