### ISSUE TITLE
Event не отражает все события

### ISSUE THREAD

**Issue by Almeonamy** [morpher-ru/Yandex.Checkout.V3#3]
В enum Event сейчас зафиксирован только один тип события: PaymentWaitingForCapture. 
https://kassa.yandex.ru/docs/guides/#platezhi

**Comment by Almeonamy** [comment]
Event некорректно парсится из уведомления от Яндекса. У меня всегда он принимает значение 0.

**Comment by bzaar** [comment]
Наверное, по той же причине. Нужно убрать Converter.

**Comment by Almeonamy** [comment]
Нашёл причину. Я вставляю Message в параметры Action'а контроллера. В итоге для десериализации используется не тот сериализатор, что в библиотеке.

Логично, но не очевидно. Наверное, стоит сделать пометку об этом в документации. 

Пока не придумал, как красиво это обойти. Временно просто отключил проверку поля Event. Остальные поля парсятся корректно.

**Comment by bzaar** [comment]
Да, такого использования я не ожидал. А что, ваш сериализатор не учитывает
ConverterAttribute?
