### ISSUE TITLE
Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead

### ISSUE THREAD

**Issue by kostya7** [morpher-ru/Yandex.Checkout.V3#31]
В версии net core 3.0 происходит ошибка
`Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead`

при вызове `Client.ParseMessage(Request.Method, Request.ContentType, Request.Body);`

Callstack
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
Connection id "0HM6EGJR6099Q", Request id "0HM6EGJR6099Q:00000002": An unhandled exception was thrown by the application.
System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
at System.IO.StreamReader.ReadBuffer()
at System.IO.StreamReader.ReadToEnd()
at Yandex.Checkout.V3.Client.ReadToEnd(Stream stream)
```

статья описывающая проблему:
https://docs.microsoft.com/ru-ru/dotnet/core/compatibility/3.0

для устранения проблемы можно использовать код перед вызовом метода (можно также отключить глобально):
```
var syncIOFeature = HttpContext.Features.Get<IHttpBodyControlFeature>();
            if (syncIOFeature != null)
            {
                syncIOFeature.AllowSynchronousIO = true;
}
```

**Comment by bzaar** [comment]
Я [добавил](https://github.com/morpher-ru/Yandex.Checkout.V3/pull/32) ParseMessageAsync(). Можете попробовать?

**Comment by kostya7** [comment]
все в порядке, спасибо за быстрый ответ

**Comment by bzaar** [comment]
Опубликовал https://www.nuget.org/packages/Yandex.Checkout.V3/1.1.0
