### ISSUE TITLE
Входящие уведомления о изменении статуса возврата

### ISSUE THREAD

**Issue by savalik** [morpher-ru/Yandex.Checkout.V3#37]
Здраствуйте!

Читаю документацию на сайте yookassa, смотрю на данный .NET клиент, смотрю на sdk для python и не могу понять - чего ожидать при обработке уведомлений об успешном возврате платежа?

На сайте примеров запроса нет, в [sdk python](https://github.com/yoomoney/yookassa-sdk-python/blob/master/docs/examples/01-configuration.md#%D0%92%D1%85%D0%BE%D0%B4%D1%8F%D1%89%D0%B8%D0%B5-%D1%83%D0%B2%D0%B5%D0%B4%D0%BE%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F) из уведомления извлекаются `event`, `refundId`, `refundStatus` и `paymentId`.
Однако в .NET клиенте извлекаются `Event` который можно интерпретировать как `refundStatus` и `Object`, который типизирован как `Payment`. Я догадываюсь, что `refundId` в данном случае будет поле `Message.Object.Id`, но где тогда поле `paymentId`? И есть ли где-то описание этого поведения?
Из песочницы запросы уведомлений не приходят, поэтому как разобраться самому в данном вопросе - я не понимаю.

**Comment by bzaar** [comment]
Насколько я понял из документации, в случае, когда `event == refund.succeeded`, `object` будет типа `Refund`, а не `Payment`, и id платежа будет в `object.paymentId`. Боюсь, что сейчас библиотека не сможет правильно распарсить уведомление о возврате. Вам нужно будет это сделать самостоятельно.

**Comment by savalik** [comment]
Предлагаю пока оставить issue открытым, чтобы другие разработчики могли проще найти данный ответ. Спасибо!

**Comment by balkarov** [comment]
@bzaar 
Добрый день. А когда планируется доработать библиотеку, чтобы она работала с refund?

**Comment by bzaar** [comment]
@balkarov, добрый день! Планов особых нет, но пул-реквесты приветствуются! :)

**Comment by bzaar** [comment]
Сделано: fb0d84704dfe9a575f4cc4f5bed7efff06d03a08

Если вас устраивает данное решение, прошу закрыть issue.
