### ISSUE TITLE
Сериализация enum

### ISSUE THREAD

**Issue by Almeonamy** [morpher-ru/Yandex.Checkout.V3#4]
При сериализации enum в итоговый json подставляется строковое значение названия элемента enum. Яндекс требует числовое значение.

Например, при отправке данных чека отправляется VatCode со значением NoVat. В json отправляется строковое значение "NoVat".  Яндекс возвращает ошибку, потому что ожидает числовое значение 1.

**Comment by bzaar** [comment]
Добрый день!  Спасибо, что написали об ошибке. Да, нужно свериться с
документацией. Скорее всего, это не единственный enum, от которого
требуется такое поведение. Чтобы посылалось число, нужно убрать строку

[JsonConverter(typeof(StringEnumConverter))]

https://github.com/morpher-ru/Yandex.Checkout.V3/blob/master/Yandex.Checkout.V3/VatCode.cs#L9

У вас есть возможность протестировать и сделать pull request?  Тогда я смог
бы выпустить новую версию уже сегодня.

**Comment by Almeonamy** [comment]
Похоже, что это единственный такой enum. От других требуется строковое значение. Постараюсь сегодня протестировать.

**Comment by Almeonamy** [comment]
Протестировал. Работает. Но pull request сделать сегодня не успел.

**Comment by bzaar** [comment]
Спасибо!  И Event десериализуется правильно?

**Comment by Almeonamy** [comment]
Прошу прощения за задержку. Сделал pull request проверенной сериализации VatCode.
https://github.com/morpher-ru/Yandex.Checkout.V3/pull/5

По поводу Event. Дело в том, что в Asp.Net MVC 5 для десериализации при биндинге параметров используется JavaScriptSerializer. Он игнорирует атрибут JsonConverter. Я попытался заменить сериализатор на Json.NET, но вышло только на половину. Asp.Net сначала десериализует входные данные в объект dynamic, и только затем этот объект приводится к типу, указанному в параметре. В этом случае JsonConverter тоже игнорируется, т.к. нужный тип не используется в процессе десериализации.

В итоге пришлось напрямую брать строку json из тела запроса и десериализовать вручную.
```c#
Request.InputStream.Position = 0;
var notificationJson = new StreamReader(Request.InputStream).ReadToEnd();
var message = JsonConvert.DeserializeObject<Message>(notificationJson);
```

**Comment by bzaar** [comment]
Закрыто в #5.
