### ISSUE TITLE
Проблема с Newtonsoft.Json

### ISSUE THREAD

**Issue by dasedd** [morpher-ru/Yandex.Checkout.V3#42]
Тут ( и в Nuget пакете ) используется старая версия Newtonsoft.Json, из-за этого возникает конфликт с другими библиотеками, которые используют более свежую версию (> 10.0.03)

**Comment by bzaar** [comment]
Да, пакет Newtonsoft.Json используется очень многими приложениями и библиотеками. Маловероятно, что все они будут использовать одну и ту же версию. Это типичная проблема [Diamond Dependencies](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/dependencies#diamond-dependencies). В .NET Core+ эта проблема решается автоматически, а в .NET Framework традиционное решение - это [binding redirects](https://nickcraver.com/blog/2020/02/11/binding-redirects/#the-fix-if-youre-using-net-framework). Обычно чтобы добавить binding redirect, достаточно дабл-кликнуть на сообщение об ошибке в Visual Studio.

**Comment by dasedd** [comment]
> Да, пакет Newtonsoft.Json используется очень многими приложениями и библиотеками. Маловероятно, что все они будут использовать одну и ту же версию. Это типичная проблема [Diamond Dependencies](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/dependencies#diamond-dependencies). В .NET Core+ эта проблема решается автоматически, а в .NET Framework традиционное решение - это [binding redirects](https://nickcraver.com/blog/2020/02/11/binding-redirects/#the-fix-if-youre-using-net-framework). Обычно чтобы добавить binding redirect, достаточно дабл-кликнуть на сообщение об ошибке в Visual Studio.

спасибо!
