### ISSUE TITLE
Ошибка при создании Deal

### ISSUE THREAD

**Issue by anahit-aleksanyan** [morpher-ru/Yandex.Checkout.V3#43]
Привет.
Я пытаюсь интегрировать YooMany в свой основной проект веб-API .Net, используя "Yandex.Checkout.V3" Version="1.6.0"

На этапе создания сделки я получаю это исключение - 'This store can't use Safe deal. Contact the YooMoney manager to learn more'.
![Screenshot (437)_LI](https://user-images.githubusercontent.com/97456998/163816831-63938f63-6dc6-4a26-8d2f-a100881584de.jpg)

Подскажите пожалуйста причину этой ошибки.

**Comment by bzaar** [comment]
Добрый день! Я думаю, что причина в том, что вашему магазину не разрешено использовать безопасную сделку. Как написано в сообщении об ошибке, contact the YooMoney manager to learn more. :)

**Comment by anahit-aleksanyan** [comment]
> Добрый день! Я думаю, что причина в том, что вашему магазину не разрешено использовать безопасную сделку. Как написано в сообщении об ошибке, contact the YooMoney manager to learn more. :)

Спасибо !!!
