### ISSUE TITLE
Библиотека рабочая?

### ISSUE THREAD

**Issue by Varyna** [morpher-ru/Yandex.Checkout.V3#46]
Добрый денью Библиотека рабочая? Пытаюсь реализовать, не выходит.
1)	Ссылки на Яндекс не рабочие у вас в инструкции;
2)	Теперь нету secretKey  вроде как это теперь Идентификатор приложения (client_id);
3)	shopId тоже нету теперь

**Comment by bzaar** [comment]
Добрый день! Более 20 скачиваний в день, и никто, кроме вас, пока не жаловался.

1. Ссылки на Яндекс [поменял](https://github.com/morpher-ru/Yandex.Checkout.V3/commit/5ac3faadc721545a106cfe8f14142284b43cc6fc), спасибо! Раньше работало перенаправление, теперь перестало. Если заметите еще нерабочие ссылки, сообщите, пожалуйста.
2. Вы, вероятно, говорите про [API для партнеров](https://yookassa.ru/developers/solutions-for-platforms/partners-api/basics). Его данная библиотека не поддерживает.
3. ShopID есть в [API принятия платежей](https://yookassa.ru/developers/payment-acceptance/getting-started/quick-start), который данная библиотека как раз поддерживает.
