### ISSUE TITLE
Ошибка  Yandex.Checkout.V3.YandexCheckoutException: 'Receipt is missing or illegal'

### ISSUE THREAD

**Issue by Nevega** [morpher-ru/Yandex.Checkout.V3#51]
Добрый день

при переключении с тестового на  боевой токен
в момент отправки  платежа 
вот такая  ошибка:

Yandex.Checkout.V3.YandexCheckoutException: 'Receipt is missing or illegal'
This exception was originally thrown at this call stack:
    Yandex.Checkout.V3.Client.ProcessResponse<T>(System.Net.HttpStatusCode, string, string) in Client.cs
    Yandex.Checkout.V3.Client.GetResponse<T>(System.Net.HttpWebResponse) in Client.cs
    Yandex.Checkout.V3.Client.Query<T>(string, object, string, string) in Client.cs
    Yandex.Checkout.V3.Client.CreatePayment(Yandex.Checkout.V3.NewPayment, string) in Client.cs
    RMC_IEM.YandexKassa.YandexPayment.MakePayment(decimal, string) in YandexPayment.cs
    RMC_IEM.BusinessLogic.RetailLogic.YandexKassaLogic.YandexKassaCase.YandexMakePaymentUrl(decimal, string) in YandexKassaCase.cs
    RMC_IEM.Retail.Pages.OrderSuccsessPage.MakePayment() in OrderSuccsessPage.razor
    Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync<T>(System.MulticastDelegate, T) in EventCallbackWorkItem.cs
    Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(Microsoft.AspNetCore.Components.EventCallbackWorkItem, object) in ComponentBase.cs
    Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(ulong, Microsoft.AspNetCore.Components.RenderTree.EventFieldInfo, System.EventArgs) in Renderer.cs

**Comment by bzaar** [comment]
Судя по сообщению об ошибке, от вас требуют чек, а вы его не присылаете.

Данные чека кладутся в `newPayment.Receipt`:

```
    NewPayment newPayment = new()
    {
        Receipt = new()
        {
            Customer = new() {...},
            Items = new() {...}
        }
    };
```
Как-то так.

**Comment by Nevega** [comment]
спасибо за подсказку, буду искать что за чек от меня  хотят

**Comment by Nevega** [comment]
Разобрался спасибо.

**Comment by Nevega** [comment]
ахах похоже с  Blazor - SignalR, не дружит   clientProxy.SendCoreAsync, блин
