### ISSUE TITLE
Get PaymentObject in ReturnURL

### ISSUE THREAD

**Issue by AliA74** [morpher-ru/Yandex.Checkout.V3#52]
Hello sir,

Are you aware of how to recieve payment object after payment succeeded and user is returned to _ReturnUrl_. I see that _Client.ParseMessage_ expects a Post request, but I recieve a Get Request without any query parameters so it is not possible to identify from which payment user has landed on _ReturnUrl_.

**Comment by bzaar** [comment]
Hi, sorry I missed your question. 

Have you set the notifications URL in settings? 

https://yookassa.ru/my/merchant/integration/http-notifications

**Comment by bzaar** [comment]
Feel free to reopen if you have more questions.
