### ISSUE TITLE
ReceiptItem and PaymentNotification

### ISSUE THREAD

**Issue by Tumanov21** [morpher-ru/Yandex.Checkout.V3#55]
Здравствуйте! 

Хотелось узнать как правильно проводить оплату с чеком. Т.к. в скриншоте (см.платеж с чеком) добавлены параметры при этом выдается ошибка (см. ошибка платеж с чеком). Методом тыка было определено, что ошибка заключается в параметрах Description или Amount, но при этом не понятно в чем не корректность ввода данных. Оплата без чека проходит. 

Так же хотелось бы узнать каким образом нужно подключится к уведомлению об оплате от юкассы т.к. от примера кода указаном в AspNetSimple(Default.aspx.cs) не работает.

Разработка ведется на API .NET 7 

![Ошибка платежа с чеком](https://github.com/morpher-ru/Yandex.Checkout.V3/assets/93746032/f95fe74d-1f0e-4864-a10c-400bf8110033)
)
![Пример платежа с чеком](https://github.com/morpher-ru/Yandex.Checkout.V3/assets/93746032/6f6c168a-ac0d-459c-950b-69cb9acb32ac)

**Comment by Tumanov21** [comment]
Проблема с чеком не  актуальна. Решение оказалось в пробелах телефонного номера

**Comment by bzaar** [comment]
Этот тикет можно закрыть?

**Comment by Tumanov21** [comment]
> Этот тикет можно закрыть?
Да
