### ISSUE TITLE
please make QueryAsync public i need extend GetRufundsAsync to pass url params

### ISSUE THREAD

**Issue by zamap** [morpher-ru/Yandex.Checkout.V3#56]
private async Task<T> QueryAsync<T>(HttpMethod method, object body, string url, string idempotenceKey, CancellationToken cancellationToken)

**Comment by bzaar** [comment]
Could you raise a PR with the changes you want to make to GetRefundAsync()? So other can benefit from these changes rather than having to re-implement them.

**Comment by zamap** [comment]
I need api to get refund list https://yookassa.ru/developers/api?codeLang=bash#get_refunds_list
there are plenty of params that can be passed in https://yookassa.ru/developers/api?codeLang=bash#get_refunds_list right now i need payment_id

**Comment by zamap** [comment]
https://github.com/morpher-ru/Yandex.Checkout.V3/pull/59

**Comment by zamap** [comment]
https://github.com/morpher-ru/Yandex.Checkout.V3/pull/58
https://github.com/morpher-ru/Yandex.Checkout.V3/pull/57

**Comment by bzaar** [comment]
It looks like what you really want is to add a new method called GetRefunds[Async] similar to the existing method GetReceipts[Async]? No need to make QueryAsync public. If so, please update the title of this issue to "Add GetRefunds[Async]"

**Comment by bzaar** [comment]
I've impemented GetRefunds[Async] here: 31049faf1ce416cec204512173feaec953506352

Could you download the package from [here](https://ci.appveyor.com/project/morpher/yandex-checkout-v3/builds/49687229/artifacts) and give it a test?

**Comment by bzaar** [comment]
I'm not quite sure if URL encoding the query params is needed. Could you test [with](https://ci.appveyor.com/project/morpher/yandex-checkout-v3/builds/49690802/artifacts) and [without](https://ci.appveyor.com/project/morpher/yandex-checkout-v3/builds/49687229/artifacts) it?

**Comment by bzaar** [comment]
Could you grab the [latest package](https://ci.appveyor.com/project/morpher/yandex-checkout-v3/builds/49703667/artifacts) and check if it does what you need?

**Comment by zamap** [comment]
is it ok? https://ci.appveyor.com/project/morpher/yandex-checkout-v3/builds/49703667/messages, .netcoreapp2.0 is out of support

**Comment by zamap** [comment]
why CancellationTokenand and IdempotenceKey inside ListOptions?

**Comment by zamap** [comment]
why CancellationTokenand and IdempotenceKey inside ListOptions?

**Comment by zamap** [comment]
in response  of GetReceiptsAsync i see Yandex.Checkout.V3.Receipt type does not correspond to https://yookassa.ru/developers/api#receipt_object,  can ReceiptInformation be used instead ?

**Comment by bzaar** [comment]
Closing as all child issues are resolved.
