### ISSUE TITLE
Пустой Content-Type в запросах без body в AsyncClient

### ISSUE THREAD

**Issue by SonicGD** [morpher-ru/Yandex.Checkout.V3#6]
Добрый день. Нашёл проблему при попытке использовать метод 
```csharp
CapturePaymentAsync(
      string id,
      string idempotenceKey = null,
      CancellationToken cancellationToken = default (CancellationToken))
```
Этот метод посылает запрос с `body = null`. При этом в методе `CreateRequest` следующий код:
```csharp
if (body != null)
{
     request.Content = new StringContent(Serializer.SerializeObject(body), Encoding.UTF8, Client.ApplicationJson);
}
```
То есть если `body` пустое, то контент у запроса не задаётся, а вместе с ним и заголовки, в частности `Content-Type`. В итоге Яндекс отбивает запрос с ошибкой `415 Unsupported Media Type`.

Надо либо всегда выставлять контент, пусть он и нулевой длины будет, либо заголовки прописывать у самого запроса.

**Comment by bzaar** [comment]
Добрый день! Спасибо, что сообщили о проблеме. Можете попробовать версию из PR #7? Если все в порядке, то выпущу новую версию.

**Comment by SonicGD** [comment]
День добрый. Проверил, работает. Ждём релиза, спасибо =)

**Comment by bzaar** [comment]
Новая версия опубликована: https://www.nuget.org/packages/Yandex.Checkout.V3/0.1.2

**Comment by SonicGD** [comment]
Спасибо
