### ISSUE TITLE
in response  of GetRefundsAsync i see Yandex.Checkout.V3.Receipt type does not correspond to https://yookassa.ru/developers/api#receipt_object,  can ReceiptInformation be used instead ?

### ISSUE THREAD

**Issue by bzaar** [morpher-ru/Yandex.Checkout.V3#61]
in response  of GetRefundsAsync i see Yandex.Checkout.V3.Receipt type does not correspond to https://yookassa.ru/developers/api#receipt_object,  can ReceiptInformation be used instead ?

_Originally posted by @zamap in https://github.com/morpher-ru/Yandex.Checkout.V3/issues/56#issuecomment-2082022675_

**Comment by bzaar** [comment]
@zamap

```GetRefundsAsync``` returns ```IAsyncEnumerable<Refund>```:

https://github.com/morpher-ru/Yandex.Checkout.V3/blob/900703129580a72631ce4650557db26304361703/Yandex.Checkout.V3/AsyncClient.Enumerable.cs#L29

Did you mean GetReceiptsAsync?

**Comment by bzaar** [comment]
Can I see the response you are getting?

**Comment by zamap** [comment]
yes it was about GetReceiptsAsync  in result i expect a list of 
    public class ReceiptInformation
    {
        public string Id { get; set; }

        /// <summary>
        /// Тип чека в онлайн-кассе
        /// </summary>
        public SettlementReceiptType Type { get; set; }

        /// <summary>
        /// Идентификатор платежа, для которого был сформирован чек
        /// </summary>
        public string PaymentId { get; set; }

        /// <summary>
        /// Идентификатор возврата, для которого был сформирован чек. Отсутствует в чеке платежа
        /// </summary>
        public string RefundId { get; set; }

        /// <summary>
        /// Статус доставки данных для чека в онлайн-кассу
        /// </summary>
        public ReceiptStatus Status { get; set; }

        /// <summary>
        /// Номер фискального документа
        /// </summary>
        public string FiscalDocumentNumber { get; set; }

        /// <summary>
        /// Номер фискального накопителя в кассовом аппарате
        /// </summary>
        public string FiscalStorageNumber { get; set; }

        /// <summary>
        /// Фискальный признак чека. Формируется фискальным накопителем на основе данных, переданных для регистрации чека
        /// </summary>
        public string FiscalAttribute { get; set; }

        /// <summary>
        /// Дата и время формирования чека в фискальном накопителе
        /// </summary>
        public DateTime? RegisteredAt { get; set; }

        /// <summary>
        /// Идентификатор чека в онлайн-кассе. Присутствует, если чек удалось зарегистрировать
        /// </summary>
        public string FiscalProviderId { get; set; }

        /// <summary>
        /// Система налогообложения, <see cref="TaxSystem"/>
        /// </summary>
        public TaxSystem? TaxSystemCode { get; set; }

        /// <summary>
        /// Список товаров в чеке (не более 100 товаров).
        /// </summary>
        public List<ReceiptItem> Items { get; set; } = new();

        /// <summary>
        /// Перечень совершенных расчетов.
        /// </summary>
        public List<Settlement> Settlements { get; set; } = new();

        /// <summary>
        /// Идентификатор магазина, от имени которого нужно отправить чек
        /// </summary>
        public string OnBehalfOf { get; set; }
    }

**Comment by bzaar** [comment]
I've added missing Receipt members in b28e3a5ca027bfe1528dda2891476bf6a0628bbc. Can you try [this package](https://ci.appveyor.com/project/morpher/yandex-checkout-v3/build/artifacts)?

**Comment by zamap** [comment]
looks like referenced package is wrong [this package](https://ci.appveyor.com/project/morpher/yandex-checkout-v3/build/artifacts)

**Comment by zamap** [comment]
smth went wrong you removed customer from receipt, but it is required to create payment https://yookassa.ru/developers/api#payment_object

**Comment by bzaar** [comment]
```NewReceipt```, which is passed in when you create a new receipt, [does have ```Customer```](https://github.com/morpher-ru/Yandex.Checkout.V3/blob/b28e3a5ca027bfe1528dda2891476bf6a0628bbc/Yandex.Checkout.V3/NewReceipt.cs#L34).

```Receipt```, which is returned from ```GetReceipts()```, does not have ```Customer``` because there's none in the [documentation](https://yookassa.ru/developers/api#receipt_object).

> smth went wrong

What do you mean? What symptoms do you see?

**Comment by zamap** [comment]
when you create payment https://yookassa.ru/developers/api#payment_object there is a payment.receipt.customer in request

**Comment by bzaar** [comment]
This should fix it: 1b5de5815dd91ec9bc1a4520d1fc212f0892b0e2 

Can you try the [latest package](https://ci.appveyor.com/project/morpher/yandex-checkout-v3/build/artifacts)?

**Comment by zamap** [comment]
https://yookassa.ru/developers/api#receipt ReceiptIndustryDetails  is an array not an object , GetReceiptsAsync failed

**Comment by bzaar** [comment]
@zamap  I'm sorry, I should have tested my code against the prod service. I'll have a look now.

**Comment by bzaar** [comment]
> ReceiptIndustryDetails is an array not an object , GetReceiptsAsync failed

I couldn't get ```GetReceiptsAsync``` to fail as my store doesn't have any receipts and I couldn't create any.

I made ReceiptIndustryDetails an array: c1a7e1c390cf124c8e84709b55a3a5c9d02d33f1. Hope this helps.

**Comment by zamap** [comment]
https://github.com/morpher-ru/Yandex.Checkout.V3/pull/64

**Comment by bzaar** [comment]
@zamap  Please let me know when you're happy with the current package and I'll push it to Nuget.

**Comment by zamap** [comment]
all fine, you can go for it

**Comment by bzaar** [comment]
@zamap Done: https://www.nuget.org/packages/Yandex.Checkout.V3/3.0.0
