### ISSUE TITLE
Why are CancellationToken and IdempotenceKey inside ListOptions?

### ISSUE THREAD

**Issue by bzaar** [morpher-ru/Yandex.Checkout.V3#62]
why CancellationTokenand and IdempotenceKey inside ListOptions?

_Originally posted by @zamap in https://github.com/morpher-ru/Yandex.Checkout.V3/issues/56#issuecomment-2082008120_

**Comment by bzaar** [comment]
@zamap 

Because they are common to all four list operations (GetReceitpts, GetRefunds...)

Otherwise, each of the four methods would have to include CancellationToken and IdempotenceKey explicitly which would create unnecessary duplication.

Why, is this a problem?

**Comment by zamap** [comment]
no problem, but in my opinion it would be great to have them separated from filter list options and use them explicitly,  and have the same behaviour for all methods

**Comment by zamap** [comment]
create payment for example accepts cancellationtoken as separate parameters, but list endpoint will hide cancellationtoken in options - that will missleading the end user of the lib

**Comment by bzaar** [comment]
Okay, I agree - having CancellationToken inside ListOptions might be confusing. I'll move it to the methods' signatures.

And we don't really need Idempotence-Key in GET requests. So that can go as well, leaving only PageSize in ListOptions.

**Comment by bzaar** [comment]
Done: 02148685fd3fddb7862beb0695c67ddee9976844

**Comment by zamap** [comment]
ct naming strategy for cancellationToken, MS do it in this way -> CancellationToken cancellationToken, but it is OK like it is right now https://github.com/morpher-ru/Yandex.Checkout.V3/commit/02148685fd3fddb7862beb0695c67ddee9976844
