### ISSUE TITLE
.netcoreapp2.0 is out of support

### ISSUE THREAD

**Issue by bzaar** [morpher-ru/Yandex.Checkout.V3#63]
is it ok? https://ci.appveyor.com/project/morpher/yandex-checkout-v3/builds/49703667/messages, .netcoreapp2.0 is out of support

_Originally posted by @zamap in https://github.com/morpher-ru/Yandex.Checkout.V3/issues/56#issuecomment-2081950233_

**Comment by bzaar** [comment]
@zamap, many sdks are out of support, .net5 included. But they're still being used, that's why we need to target them.

**Comment by bzaar** [comment]
@zamap Happy for me to close this issue?

**Comment by zamap** [comment]
yep
