### ISSUE TITLE
Payment method - Installments

### ISSUE THREAD

**Issue by Lifanov1996** [morpher-ru/Yandex.Checkout.V3#67]
Столкнулся с проблемой при выборе способа оплаты - оплата по частям
+ в библиотеке не  реализован способ оплаты в кредит или в рассрочку?

![Sc](https://github.com/morpher-ru/Yandex.Checkout.V3/assets/108743045/42353dfe-9903-46e1-b6b8-c280a556ab22)

**Comment by bzaar** [comment]
Судя по стеку, сообщение об ошибке приходит с сервера. Библиотека тут ни при чем. Обратитесь в поддержку YooMoney. [См. также](https://niantic.helpshift.com/hc/ru/48-web-store/faq/3902-my-payment-method-was-declined/#:~:text=%D0%AD%D1%82%D0%B0%20%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0%20%D0%BC%D0%BE%D0%B6%D0%B5%D1%82%20%D0%BF%D0%BE%D1%8F%D0%B2%D0%B8%D1%82%D1%8C%D1%81%D1%8F%2C%20%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0,%D1%81%D0%BF%D0%BE%D1%81%D0%BE%D0%B1%20%D0%BE%D0%BF%D0%BB%D0%B0%D1%82%D1%8B%20%D0%B4%D0%BB%D1%8F%20%D0%B7%D0%B0%D0%B2%D0%B5%D1%80%D1%88%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%B6%D0%B0.)

**Comment by Lifanov1996** [comment]
Это лог на стороне ЮКасса

![Sc1](https://github.com/morpher-ru/Yandex.Checkout.V3/assets/108743045/4e9b864d-8332-49e6-946a-b00fe7820019)

**Comment by Lifanov1996** [comment]
Проблему нашел
1. Надо ИП
2. Если магазин реализован в тг, то оплата в кредит или в рассрочку не доступна

**Comment by bzaar** [comment]
Спасибо, что поделились. Может, кому-то пригодится данная информация.

Я правильно понимаю, что проблема возникла из-за того, что в вашем профиле не было данных ИП?

**Comment by Lifanov1996** [comment]
Вы правильно поняли
Был самозанятый
Такому типу предпринимателей, оплата в кредит или в рассрочку не доступна
