### ISSUE TITLE
Поддержка выплат

### ISSUE THREAD

**Issue by equaerdist** [morpher-ru/Yandex.Checkout.V3#70]
Поддерживает ли данная библиотека выплаты?
Хотел сначала реализовать создание выплаты с использованием данных карты напрямую, однако не нашел метода, который принимает объект Payout, который и содержит данные для карты. Решил использовать NewPayout, предварительно получив токен для карты уже от юкассы, вроде как все отправляется. Но теперь не могу найти класса об успешной выплате для уведомлений, как например для оплаты(PaymentWaitingForCaptureNotification). Возможно, я невнимательно смотрел, но в Issue не обнаружил ответа на данную тему.

**Comment by bzaar** [comment]
Все верно, для создания выплаты предназначен метод CreatePayout[Async], принимающий объект NewPayout.

В библиотеке до данного момента не было классов для десериализации уведомлений о выплатах, но я их только что добавил в пул-реквесте #72. Можете вас попросить протестировать этот код?

**Comment by equaerdist** [comment]
> Все верно, для создания выплаты предназначен метод CreatePayout[Async], принимающий объект NewPayout.
> 
> В библиотеке до данного момента не было классов для десериализации уведомлений о выплатах, но я их только что добавил в пул-реквесте #72. Можете вас попросить протестировать этот код?

Да, хорошо. Хотел бы уточнить у вас, как я понял из документации, для выплат и платежей мы используем разные credentials и соответственно не получится инициализировать универсальный клиент сразу в DI? Пары (agentId, secretKey) и (shopId, secretKey).

**Comment by equaerdist** [comment]
> Все верно, для создания выплаты предназначен метод CreatePayout[Async], принимающий объект NewPayout.
> 
> В библиотеке до данного момента не было классов для десериализации уведомлений о выплатах, но я их только что добавил в пул-реквесте #72. Можете вас попросить протестировать этот код?

Мне удалось протестировать и это отлично работает(по крайней мере для PayoutSuccess)

**Comment by bzaar** [comment]
Большое вам спасибо за тестирование! Опубликовал версию 4.2.0 с этими изменениями: https://www.nuget.org/packages/Yandex.Checkout.V3/4.2.0
