### ISSUE TITLE
Идеи для версии 5.0.0

### ISSUE THREAD

**Issue by bzaar** [morpher-ru/Yandex.Checkout.V3#71]
Предлагаю добавлять сюда идеи, как можно улучшить API библиотеки, ломающие обратную совместимость, для включения в версию 5.0.0.

Например, обязательные для заполнения свойства, такие как Amount в NewPayment, сейчас не являются обязательными:

```
    public Amount Amount { get; set; }
```
лучше заменить на:
```
    public Amount Amount { get; init; }
```
Тогда их обязательность станет более очевидной пользователям библиотеки.

**Comment by Ch0bits** [comment]
Здравствуйте. Во первых спасибо за ваш труд.
Изменение не ломающее, но хочется добавить поддержку события "deal.closed" в Client.ParseMessage

**Comment by ExLuzZziVo** [comment]
Здравствуйте, можно еще перейти с библиотеки **Newtonsoft.Json** на более производительную **System.Text.Json**

**Comment by NUNJax** [comment]
Добрый день. Спасибо за проект. Подключаю его на MVC 5 Net framework 4.7. Столкнулся с проблемой, это единственное подходящее место для вопроса которое я нашел.
Оплату провожу без подтверждения платежа, в создании платежа прописал Capture = true,
Вся оплата проходит успешно, могу вручную запросить статус и уже применять его для отметки оплаты в заказе.
Я не понимаю как принять и обработать уведомление от Юкассы для автоматической обработки. В Кабинете Юкассы прописал URL для уведомлений (https://c....ru/S...t/PayOrderResult), выбрал payment.succeeded и payment.canceled. Как тестировать автоматические уведомления если я не могу прописать в Юкассе ссылку на LocalHost? только в VS я могу отловить ошибку.
В Контроллере у меня следующий код , как из примера (сюда ведет URL с Юкассы)
```
public void PayOrderResult(object sender, EventArgs e)
{
    try
    {
        var notification = Yandex.Checkout.V3.Client.ParseMessage(Request.HttpMethod, Request.ContentType, Request.InputStream);
        if (notification is PaymentSucceededNotification paymentSucceededNotification)
        {                    
            Payment payment = paymentSucceededNotification.Object;            
            if (payment.Paid)
            {
                var order = db.Orders.SingleOrDefault(pid => pid.PaymentId == payment.Id);
                if (order != null)
                {
                    order.PaymentStatus = "succeeded";
                    db.Entry(order).State = EntityState.Modified;
                    db.SaveChanges();
                }
           ......
    }
    catch  {    }
}
```
Код не срабатывает, В таблицу order не пишется статус успешной оплаты. При этом фактически оплата проходит успешно.
Подскажите как можно подправить код, или как можно отследить уведомление от Юкассы в VS на LocalHost.
Извиняюсь если здесь такое писать нельзя, в этом случае направьте пожалуйста в правильное место. Для связи в случае необходимости удаления сообщения. nunjax@gmail.com

**Comment by bzaar** [comment]
Почему-то все начали писать в эту тему, причем предложения, не связанные с нарушением совместимости. Лучше [открывайте новые темы](https://github.com/morpher-ru/Yandex.Checkout.V3/issues/new).
