### ISSUE TITLE
SberPay с телефоном и без телефона

### ISSUE THREAD

**Issue by IlyaBarkov** [morpher-ru/Yandex.Checkout.V3#73]
При создании нового платежа можно заранее указать фиксированный способ оплаты. 
Например, для СБП указываю
`PaymentMethodData = PaymentMethod.Sbp()`

А для СберПей надо указать код вида
`PaymentMethodData = PaymentMethod.Sberbank("79251234567")`

То есть номер телефона надо запрашивать у клиента заранее и подавать его в метод. 
Но согласно документации Юкассы https://yookassa.ru/developers/payment-acceptance/integration-scenarios/manual-integration/sberpay — номер телефона является необязательным параметром. 
В случае, если телефон не указан, Юкасса сама запросит его у покупателя на странице платежа. 
Оба варианта (и с телефоном, и без телефона) описаны на странице документации. 

Но SDK позволяет реализовать только вариант с заранее прописанным номером телефона. 
Возможно ли сделать обновление SDK, при котором метод оплаты PaymentMethod.Sberbank не будет запрашивать номер телефона как обязательный параметр?

**Comment by bzaar** [comment]
Метод Sberbank(string phone) необязательный и введен только для удобства (для тех, кто знает номер телефона заранее):

```
    public static PaymentMethod Sberbank(string phone) => new()
    {
        Type = PaymentMethodType.Sberbank,
        Phone = phone
    };
```

Вы можете сами создать PaymentMethod, не указывая номер телефона:

```
    var paymentMethod = new PaymentMethod 
    {
        Type = PaymentMethodType.Sberbank
    };
```
