### ISSUE TITLE
Cancellation details в Refund

### ISSUE THREAD

**Issue by negrime** [morpher-ru/Yandex.Checkout.V3#78]
Привет! В [доке объекта Refund](https://yookassa.ru/developers/api#refund_object) могут вернуться детали отмены возврата, если возврат в статусе Canceled.
Сейчас в реализации отсутствует поддержка cancellation_details.

`canceled — возврат отменен, инициатор и причина отмены указаны в объекте cancellation_details (финальный и неизменяемый статус).`

Готов реализовать

**Comment by bzaar** [comment]
Добрый день! Да, реализуете, пожалуйста.

**Comment by negrime** [comment]
Создал [PR](https://github.com/morpher-ru/Yandex.Checkout.V3/pull/79)
